title: NET Lab
email: lundrigan@byu.edu
description: >
  The Network Enhanced Technologies Lab (NET) at Brigham Young University is focused on building real systems that enhance and extend wireless networks, Internet of Things, security, privacy, and reliability.

baseurl: ""
url: http://netlab.byu.edu

markdown: kramdown
exclude: ['.gitignore', 'Makefile', 'README.md', 'CNAME']

colors: ['#ED3F95', '#F89938', '#D8E022', '#00A775', '#89298E', '#76C044', '#00AEEF']
