name: Ruby

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1.81.0
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Building website
        run: make build

      - name: Uploading website
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} -r _site/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:groups/net-lab/www/
